### ISSUE TITLE
What's the difference with `sphinxawesome_theme.docsearch`?

### ISSUE THREAD

**Issue by astrojuanlu** [algolia/sphinx-docsearch#15]
As per title 😊 We noticed that Awesome Sphinx Theme (_amazing_ theme by the way) has its own DocSearch extension:

https://sphinxawesome.xyz/how-to/configure/#bundled-extensions

https://github.com/kai687/sphinxawesome-theme/blob/dfc68e7ad90eed836fc7b38cb5d52674e104b6df/docs/conf.py#L31

Are there any practical differences?

Context: we want to adopt this (or the other) extension for Kedro https://github.com/kedro-org/kedro/issues/2932

**Comment by astrojuanlu** [comment]
Perfect, thanks for the clarification! Closing this issue

**Comment by stichbury** [comment]
Thanks @kai687 🙏
